name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install client dependencies
        working-directory: ./client
        run: npm install

      - name: Build Client
        working-directory: ./client
        run: npm run build

      - name: Install server dependencies
        working-directory: ./server
        run: npm install

      - name: Start Server
        working-directory: ./server
        run: npm start

      - name: Deploy to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.ec2-18-217-2-172.us-east-2.compute.amazonaws.com }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/*"
          target: "/var/www/html/"

